IMG_HD = "IMG_HD.BIN"
IMG_BD = "IMG_BD.BIN"

IG_MSG = "IG_MSG.OBJ"

IG_MSG_E = "IG_MSG_E.OBJ"
IG_MSG_F = "IG_MSG_F.OBJ"
IG_MSG_G = "IG_MSG_G.OBJ"
IG_MSG_S = "IG_MSG_S.OBJ"
IG_MSG_I = "IG_MSG_I.OBJ"

M_EVENTS = "M0_EVENT.OBJ", "M1_EVENT.OBJ", "M2_EVENT.OBJ", "M3_EVENT.OBJ", "M4_EVENT.OBJ"

M_EVENTS_E = "M0_EVENT_E.OBJ", "M1_EVENT_E.OBJ", "M2_EVENT_E.OBJ", "M3_EVENT_E.OBJ", "M4_EVENT_E.OBJ"
M_EVENTS_F = "M0_EVENT_F.OBJ", "M1_EVENT_F.OBJ", "M2_EVENT_F.OBJ", "M3_EVENT_F.OBJ", "M4_EVENT_F.OBJ"
M_EVENTS_G = "M0_EVENT_G.OBJ", "M1_EVENT_G.OBJ", "M2_EVENT_G.OBJ", "M3_EVENT_G.OBJ", "M4_EVENT_G.OBJ"
M_EVENTS_S = "M0_EVENT_S.OBJ", "M1_EVENT_S.OBJ", "M2_EVENT_S.OBJ", "M3_EVENT_S.OBJ", "M4_EVENT_S.OBJ"
M_EVENTS_I = "M0_EVENT_I.OBJ", "M1_EVENT_I.OBJ", "M2_EVENT_I.OBJ", "M3_EVENT_I.OBJ", "M4_EVENT_I.OBJ"
